[project]
name = "laser-coiled"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "laser-core",
    "optuna",
    "optuna-integration[dask]",
    "dask",
    "coiled"
]
